// ══════════════════════════════════════════════════════
// EXPORT — COCO, YOLO, Project JSON
// ══════════════════════════════════════════════════════
import { state, ann }     from './state.js';
import { currentImage }   from './canvas.js';
import { downloadJSON, loadImageDims } from './utils.js';

// ── Shared: collect dimensions for all (or annotated) images ──

async function collectImageDims(p, { onlyAnnotated = false } = {}) {
  const dims = {};
  if (currentImage) {
    dims[p.images[ann.imgIndex].filename] = {
      w: currentImage.naturalWidth,
      h: currentImage.naturalHeight,
    };
  }
  for (const img of p.images) {
    if (dims[img.filename]) continue;
    if (onlyAnnotated && img.boxes.length === 0) continue;
    const handle = state.fileHandles[img.filename];
    if (!handle) continue;
    const d = await loadImageDims(handle);
    if (d) dims[img.filename] = d;
  }
  return dims;
}

// ── COCO ──────────────────────────────────────────────

export async function exportCOCO() {
  const p = state.current;
  if (!p) return;

  const dims       = await collectImageDims(p);
  const categories = p.classes.map((name, i) => ({ id: i + 1, name, supercategory: 'object' }));
  const images     = [];
  const cocoAnns   = [];
  let annId = 1;

  p.images.forEach((img, imgIdx) => {
    const d = dims[img.filename];
    if (!d) return;
    const imageId = imgIdx + 1;
    images.push({ id: imageId, file_name: img.filename, width: d.w, height: d.h });

    img.boxes.forEach(box => {
      cocoAnns.push({
        id: annId++,
        image_id: imageId,
        category_id: box.classIdx + 1,
        bbox: [
          Math.round(box.x * 10) / 10,
          Math.round(box.y * 10) / 10,
          Math.round(box.w * 10) / 10,
          Math.round(box.h * 10) / 10,
        ],
        area: Math.round(box.w * box.h * 10) / 10,
        segmentation: [],
        iscrowd: 0,
      });
    });
  });

  downloadJSON({
    info: { description: `${p.name} — Toni's Simple Image Annotator`, version: '1.0', year: new Date().getFullYear() },
    licenses: [],
    categories,
    images,
    annotations: cocoAnns,
  }, `${p.name}_coco.json`);
}

// ── YOLO ──────────────────────────────────────────────

export async function exportYOLO() {
  const p = state.current;
  if (!p) return;

  const dims = await collectImageDims(p, { onlyAnnotated: true });
  const zip  = new JSZip();

  // data.yaml for Ultralytics YOLOv8
  const namesBlock = p.classes.map((c, i) => `  ${i}: ${c}`).join('\n');
  zip.file('data.yaml', [
    '# Generated by Toni\'s Simple Image Annotator',
    '# Place your images in an images/ folder next to labels/',
    'path: .',
    'train: images',
    'val: images',
    '',
    `nc: ${p.classes.length}`,
    `names:\n${namesBlock}`,
    '',
  ].join('\n'));

  // classes.txt (some tools still use this)
  zip.file('classes.txt', p.classes.join('\n'));

  // Label files under labels/
  p.images.forEach(img => {
    if (img.boxes.length === 0) return;
    const d = dims[img.filename];
    if (!d) return;
    const lines = img.boxes.map(box => {
      const cx = (box.x + box.w / 2) / d.w;
      const cy = (box.y + box.h / 2) / d.h;
      const nw = box.w / d.w;
      const nh = box.h / d.h;
      return `${box.classIdx} ${cx.toFixed(6)} ${cy.toFixed(6)} ${nw.toFixed(6)} ${nh.toFixed(6)}`;
    });
    zip.file('labels/' + img.filename.replace(/\.[^.]+$/, '') + '.txt', lines.join('\n'));
  });

  const blob = await zip.generateAsync({ type: 'blob' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href = url; a.download = `${p.name}_yolo.zip`; a.click();
  URL.revokeObjectURL(url);
}

// ── Project JSON ──────────────────────────────────────

export function exportProjectJSON() {
  const p = state.current;
  if (!p) return;
  downloadJSON(p, `${p.name}_annotator.json`);
}

// Expose for HTML onclick
window.exportCOCO        = exportCOCO;
window.exportYOLO        = exportYOLO;
window.exportProjectJSON = exportProjectJSON;
