import type { Project } from '$lib/types';
import { open } from '@tauri-apps/plugin-dialog';
import { writeTextFile, readTextFile, readDir, mkdir, exists, copyFile } from '@tauri-apps/plugin-fs';
import { convertFileSrc } from '@tauri-apps/api/core';
import { join } from '@tauri-apps/api/path';

// ── Pick folder ───────────────────────────────────────

export { pickExportFolder } from './coco';

// ── Export ─────────────────────────────────────────────

export async function runYOLOExport(
  project: Project,
  dirPath: string,
  trainRatio: number,
  onProgress: (current: number, total: number) => void,
  shouldCancel: () => boolean,
): Promise<void> {
  const imgTrainDir = await join(dirPath, 'images', 'train');
  const imgValDir = await join(dirPath, 'images', 'val');
  const lblTrainDir = await join(dirPath, 'labels', 'train');
  const lblValDir = await join(dirPath, 'labels', 'val');
  for (const d of [imgTrainDir, imgValDir, lblTrainDir, lblValDir]) {
    if (!(await exists(d))) await mkdir(d, { recursive: true });
  }

  const namesBlock = project.classes.map((c, i) => `  ${i}: ${c}`).join('\n');
  await writeTextFile(await join(dirPath, 'data.yaml'), [
    "# Generated by Toni's Simple Image Annotator",
    'path: .', 'train: images/train', 'val: images/val', '',
    `nc: ${project.classes.length}`, `names:\n${namesBlock}`, '',
  ].join('\n'));
  await writeTextFile(await join(dirPath, 'classes.txt'), project.classes.join('\n'));

  const annotated = project.images.filter(img => img.boxes.length > 0);
  const splitIdx = Math.round(annotated.length * trainRatio);

  for (let i = 0; i < annotated.length; i++) {
    if (shouldCancel()) return;

    const img = annotated[i];
    const isTrain = i < splitIdx;
    const dims = await getImageDims(project.imageDirPath, img.filename);

    if (dims) {
      const lines = img.boxes.map(box => {
        const cx = (box.x + box.w / 2) / dims.w;
        const cy = (box.y + box.h / 2) / dims.h;
        const nw = box.w / dims.w;
        const nh = box.h / dims.h;
        return `${box.classIdx} ${cx.toFixed(6)} ${cy.toFixed(6)} ${nw.toFixed(6)} ${nh.toFixed(6)}`;
      });
      const baseName = img.filename.replace(/\.[^.]+$/, '');
      await writeTextFile(await join(isTrain ? lblTrainDir : lblValDir, `${baseName}.txt`), lines.join('\n'));

      const srcPath = await join(project.imageDirPath, img.filename);
      try { await copyFile(srcPath, await join(isTrain ? imgTrainDir : imgValDir, img.filename)); } catch { /* skip */ }
    }

    onProgress(i + 1, annotated.length);
    await new Promise(r => setTimeout(r, 0));
  }
}

// ── Import ─────────────────────────────────────────────

export async function importYOLO(imageFilenames: string[], fallbackClasses?: string[]): Promise<{ classes: string[]; annotations: Record<string, { classIdx: number; x: number; y: number; w: number; h: number }[]>; needsClasses?: boolean } | null> {
  const dirPath = await open({ title: 'Select YOLO labels folder', directory: true });
  if (!dirPath) return null;

  let classes: string[] = [];
  for (const loc of [await join(dirPath as string, 'classes.txt'), await join(dirPath as string, '..', 'classes.txt')]) {
    try {
      const text = await readTextFile(loc);
      classes = text.trim().split('\n').map(s => s.trim()).filter(Boolean);
      if (classes.length > 0) break;
    } catch { /* try next */ }
  }

  if (classes.length === 0) {
    if (fallbackClasses?.length) classes = fallbackClasses;
    else return { classes: [], annotations: {}, needsClasses: true };
  }

  const annotations: Record<string, { classIdx: number; x: number; y: number; w: number; h: number }[]> = {};

  async function scanDir(dir: string) {
    let entries;
    try { entries = await readDir(dir); } catch { return; }
    for (const entry of entries) {
      if (!entry.name) continue;
      if (entry.isDirectory) { await scanDir(await join(dir, entry.name)); continue; }
      if (!entry.name.endsWith('.txt') || entry.name === 'classes.txt') continue;
      const baseName = entry.name.replace(/\.txt$/, '');
      const imgFilename = imageFilenames.find(f => f.replace(/\.[^.]+$/, '') === baseName);
      if (!imgFilename) continue;
      const text = await readTextFile(await join(dir, entry.name));
      const anns: { classIdx: number; x: number; y: number; w: number; h: number }[] = [];
      for (const line of text.trim().split('\n')) {
        const parts = line.trim().split(/\s+/).map(Number);
        if (parts.length < 5) continue;
        anns.push({ classIdx: parts[0], x: parts[1], y: parts[2], w: parts[3], h: parts[4] });
      }
      if (anns.length) annotations[imgFilename] = anns;
    }
  }

  await scanDir(dirPath as string);
  return { classes, annotations };
}

// ── Helpers ────────────────────────────────────────────

async function getImageDims(dirPath: string, filename: string): Promise<{ w: number; h: number } | null> {
  return new Promise((resolve) => {
    const src = convertFileSrc(`${dirPath}/${filename}`);
    const img = new Image();
    img.onload = () => resolve({ w: img.naturalWidth, h: img.naturalHeight });
    img.onerror = () => resolve(null);
    img.src = src;
  });
}
